/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Brand & Accent
        'primary': '#494fdf',
        'primary-bright': '#4f55f1',
        'primary-deep': '#3a40c4',
        'on-primary': '#ffffff',
        
        // Surface
        'ink': '#191c1f',
        'body': '#1f2226',
        'charcoal': '#3a3d40',
        'mute': '#505a63',
        'ash': '#5c5e60',
        'stone': '#8d969e',
        'faint': '#c9c9cd',
        'on-dark': '#ffffff',
        'on-dark-mute': 'rgba(255,255,255,0.72)',
        'canvas-light': '#ffffff',
        'canvas-dark': '#000000',
        'surface-soft': '#f4f4f4',
        'surface-card': '#ffffff',
        'surface-deep': '#0a0a0a',
        'surface-elevated': '#16181a',
        'hairline-light': '#e2e2e7',
        'hairline-dark': 'rgba(255,255,255,0.12)',
        'hairline-strong': '#191c1f',
        'divider-soft': 'rgba(255,255,255,0.06)',
        
        // Semantic
        'accent-teal': '#00a87e',
        'accent-blue-link': '#376cd5',
        'accent-light-blue': '#007bc2',
        'accent-light-green': '#428619',
        'accent-green-text': '#006400',
        'accent-yellow': '#b09000',
        'accent-warning': '#ec7e00',
        'accent-pink': '#e61e49',
        'accent-danger': '#e23b4a',
        'accent-deep-red': '#8b0000',
        'accent-brown': '#936d62',
        'link': '#376cd5',
      },
      fontFamily: {
        'display': ['Aeonik Pro', 'General Sans', 'Inter', 'sans-serif'],
        'sans': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xxl': ['136px', { lineHeight: '1.0', letterSpacing: '-2.72px', fontWeight: '500' }],
        'display-xl': ['80px', { lineHeight: '1.0', letterSpacing: '-0.8px', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '1.21', letterSpacing: '-0.48px', fontWeight: '500' }],
        'display-md': ['40px', { lineHeight: '1.2', letterSpacing: '-0.4px', fontWeight: '500' }],
        'heading-lg': ['32px', { lineHeight: '1.19', letterSpacing: '-0.32px', fontWeight: '500' }],
        'heading-md': ['24px', { lineHeight: '1.33', letterSpacing: '0', fontWeight: '500' }],
        'heading-sm': ['20px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.56', letterSpacing: '-0.09px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0.24px', fontWeight: '400' }],
        'body-md-bold': ['16px', { lineHeight: '1.5', letterSpacing: '0.16px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.43', letterSpacing: '0', fontWeight: '400' }],
        'button-lg': ['20px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        'button-md': ['16px', { lineHeight: '1.5', letterSpacing: '0.24px', fontWeight: '600' }],
        'button-sm': ['14px', { lineHeight: '1.43', letterSpacing: '0', fontWeight: '600' }],
        'caption': ['13px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        'link-emph': ['16px', { lineHeight: '1.5', letterSpacing: '0.24px', fontWeight: '700' }],
      },
      borderRadius: {
        'none': '0px',
        'sm': '8px',
        'md': '12px',
        'lg': '20px',
        'xl': '28px',
        'full': '9999px',
      },
      spacing: {
        'xxs': '4px',
        'xs': '6px',
        'sm': '8px',
        'md': '14px',
        'lg': '16px',
        'xl': '24px',
        'xxl': '32px',
        'xxxl': '48px',
        'block': '80px',
        'section': '88px',
        'band': '120px',
      },
    },
  },
  plugins: [],
};
